### ISSUE TITLE
Modify to allow wrapper to use a csv file as input file

### ISSUE THREAD

**Issue by Sarahmay84** [ictr/CLAMP_wrapper#6]
Could this be modified so that --input_file can take a csv file instead of only an excel file? I don't think the format of the --output_file necessarily needs to be changed, but it could also be modified to output a csv file as well.

**Comment by BoPeng** [comment]
I have created a PR that allows the use of .csv and .tsc (tab delimited) files as input and output file. If you are reasonably familiar with git, could you check out the `csv_format` branch of the repo and test the `clamp_wrapper.py` script? I will merge the PR once you confirm that it works as expected.

**Comment by Sarahmay84** [comment]
I've tested the clamp_wrapper.py script in the csv_format branch and it's working as expected.
